version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
 
  mongo-service:
    image: sajith75/mongo-service
    container_name: mongo-service
    depends_on:
    - mongo

  aes-encryption-service:
    image: sajith75/aes-encryption-service
    container_name: aes-encryption-service

  email-service:
    image: sajith75/email-service
    container_name: email-service
    depends_on:
    - mongo-service
    - aes-encryption-service

  secret-service:
    image: sajith75/secret-service
    container_name: secret-service
    depends_on:
    - mongo-service

  account-service:
    image: sajith75/account-service
    container_name: account-service
    depends_on:
    - mongo-service
    - secret-service

  session-token-service:
    image: sajith75/session-token-service
    container_name: session-token-service
    depends_on:
    - mongo-service
    - aes-encryption-service

  dashboard-service:
    image: sajith75/dashboard-service
    container_name: dashboard-service
    depends_on:
    - account-service
    - session-token-service

  authentication-service:
    image: sajith75/authentication-service
    container_name: authentication-service
    depends_on:
    - account-service
    - email-service
    - session-token-service

  authentication-client:
    image: sajith75/authentication-client
    container_name: authentication-client

  dashboard-client:
    image: sajith75/dashboard-client
    container_name: dashboard-client

  gateway:
    image: sajith75/gateway
    container_name: gateway
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - authentication-service
    - authentication-client
    - dashboard-service
    - dashboard-client


